-- MySQL Script generated by MySQL Workbench
-- Fri Dec  3 13:12:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vitromex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `area` (
  `nombre` VARCHAR(100) NOT NULL,
  `estatus` ENUM('Activo', 'Inactivo') NOT NULL,
  `fechaR` DATE NOT NULL,
  `fechaA` DATETIME NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login` (
  `correo` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `tipoUsuario` ENUM('Administrador', 'Supervisor') NOT NULL,
  `estatus` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`correo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supervisor` (
  `clave` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `turno` ENUM('Matutino', 'Vespertino', 'Nocturno') NOT NULL,
  `estatus` ENUM('Activo', 'Inactivo') NOT NULL,
  `login_correo` VARCHAR(50) NOT NULL,
  `area_nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`clave`),
  INDEX `fk_supervisor_login_idx` (`login_correo` ASC) ,
  INDEX `fk_supervisor_area1_idx` (`area_nombre` ASC) ,
  CONSTRAINT `fk_supervisor_login`
    FOREIGN KEY (`login_correo`)
    REFERENCES `login` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supervisor_area1`
    FOREIGN KEY (`area_nombre`)
    REFERENCES `area` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accidentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accidentes` (
  `nombreEmpleado` VARCHAR(200) NOT NULL,
  `descripcion` VARCHAR(400) NOT NULL,
  `turno` ENUM('Matutino', 'Vespertino', 'Nocturno') NOT NULL,
  `fechaA` DATETIME NOT NULL,
  `fechaR` DATETIME NOT NULL,
  `fecha` DATE NOT NULL,
  `area_nombre` VARCHAR(100) NOT NULL,
  `supervisor_clave` INT NOT NULL,
  INDEX `fk_accidentes_area1_idx` (`area_nombre` ASC) ,
  INDEX `fk_accidentes_supervisor1_idx` (`supervisor_clave` ASC) ,
  PRIMARY KEY (`fechaR`),
  CONSTRAINT `fk_accidentes_area1`
    FOREIGN KEY (`area_nombre`)
    REFERENCES `area` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accidentes_supervisor1`
    FOREIGN KEY (`supervisor_clave`)
    REFERENCES `supervisor` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tablero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tablero` (
  `tiempo` INT NOT NULL,
  `estatus` ENUM('Activo', 'Inactivo') NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador` (
  `idadministrador` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `login_correo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idadministrador`),
  INDEX `fk_administrador_login1_idx` (`login_correo` ASC) ,
  CONSTRAINT `fk_administrador_login1`
    FOREIGN KEY (`login_correo`)
    REFERENCES `login` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `calidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calidad` (
  `idcalidad` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `primera` DOUBLE NOT NULL,
  `segunda` DOUBLE NOT NULL,
  `supervisor_idsupervisor` INT NOT NULL,
  INDEX `fk_calidad_supervisor1_idx` (`supervisor_idsupervisor` ASC) ,
  PRIMARY KEY (`idcalidad`),
  CONSTRAINT `fk_calidad_supervisor1`
    FOREIGN KEY (`supervisor_idsupervisor`)
    REFERENCES `supervisor` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diasSA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diasSA` (
  `fecha` DATE NOT NULL,
  `record` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acceso` (
  `tipoUsuario` ENUM('Administrador', 'Supervisor') NOT NULL,
  `interfaz` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consumoEnergia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumoEnergia` (
  `fecha` VARCHAR(20) NOT NULL,
  `meta` DOUBLE NOT NULL,
  `final` DOUBLE NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desperdicioEsmaltes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desperdicioEsmaltes` (
  `fecha` VARCHAR(20) NOT NULL,
  `meta` DOUBLE NOT NULL,
  `final` DOUBLE NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consumoGN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumoGN` (
  `fecha` VARCHAR(20) NOT NULL,
  `meta` DOUBLE NOT NULL,
  `final` DOUBLE NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion` (
  `fecha` VARCHAR(20) NOT NULL,
  `meta` DOUBLE NOT NULL,
  `final` DOUBLE NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desperdicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desperdicio` (
  `fecha` VARCHAR(20) NOT NULL,
  `meta` DOUBLE NOT NULL,
  `final` DOUBLE NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `calidadP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calidadP` (
  `fecha` VARCHAR(20) NOT NULL,
  `meta` DOUBLE NOT NULL,
  `final` DOUBLE NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiempoVacioH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiempoVacioH` (
  `fecha` VARCHAR(20) NOT NULL,
  `meta` DOUBLE NOT NULL,
  `final` DOUBLE NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
